variable "vpc_id" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "env_prefix" {}
variable "keypair" {}
variable "ec2_type" {}
variable "myapp-sg-id" {}
variable "dbendpoint" {}
variable "alb-sg-id" {}
variable "avail_zone" {}
